Romanian translation update - the finale
angelbruni/Geckium pull request #364
Opened 2024-11-21 13:36 UTC by pmagixc

should be all good now

2024-11-21 20:42 UTC, pmagixc commented
uhh should be good

2024-11-21 21:21 UTC, angelbruni requested changes
Alright added more strings for a long requested feature. Sorry, I just remembered about it last minute.

2024-11-22 14:04 UTC, angelbruni approved these changes

2024-11-22 14:04 UTC, merged

2024-11-22 14:04 UTC, angelbruni commented
Thank you!