Translate the newly added text into Ukrainian
angelbruni/Geckium pull request #367
Opened 2024-11-21 21:51 UTC by megamanyoutuber

The title explains everything that this pull request is supposed to add.

2024-11-21 23:25 UTC, angelbruni requested changes

2024-11-21 23:25 UTC, angelbruni commented on Profile Folder/chrome/locale/uk/dtd/gsettings.dtd
> +<!ENTITY gsettings.tabManagerDescription		'Вмикає "кнопку стрілочку" зі списком відкритих вкладок у панелі вкладок'>
Would it be possible to find a way to not use "Enable" in `gsettings.tabManagerDescription` and `gsettings.enableForceColorizeAddressBar`? The toggle already implies that it's for "turning on".

2024-11-22 14:11 UTC, angelbruni requested changes

2024-11-22 14:11 UTC, angelbruni commented on Profile Folder/chrome/locale/uk/dtd/gsettings.dtd
> +<!ENTITY gsettings.enableForceColorizeAddressBar			"Вмикає темування панелей URE для несумісних дизайнів">
Would it be possible to find a way to not use "Enable" in `gsettings.enableForceColorizeAddressBar`? The toggle already implies that it's for "turning on".

2024-11-22 16:20 UTC, megamanyoutuber commented on Profile Folder/chrome/locale/uk/dtd/gsettings.dtd
> +<!ENTITY gsettings.enableForceColorizeAddressBar			"Вмикає темування панелей URE для несумісних дизайнів">
Don't think so as far as I know.

2024-11-22 16:23 UTC, angelbruni commented on Profile Folder/chrome/locale/uk/dtd/gsettings.dtd
> +<!ENTITY gsettings.enableForceColorizeAddressBar			"Вмикає темування панелей URE для несумісних дизайнів">
> Don't think so as far as I know.

I don't need any form of "Enable"/"Turn on", simply "Colorize Address Bar according to custom theme" is enough, it's just the name of the setting, nothing else.

2024-11-22 16:26 UTC, megamanyoutuber commented on Profile Folder/chrome/locale/uk/dtd/gsettings.dtd
> +<!ENTITY gsettings.enableForceColorizeAddressBar			"Вмикає темування панелей URE для несумісних дизайнів">
Ah, that would be something like "Колюрувати адресну строку по темі". I can make that into a commit on my own repository.

2024-11-22 16:28 UTC, angelbruni commented on Profile Folder/chrome/locale/uk/dtd/gsettings.dtd
> +<!ENTITY gsettings.enableForceColorizeAddressBar			"Вмикає темування панелей URE для несумісних дизайнів">
Thank you so much for your help once again, I really appreciate it :)

2024-11-22 17:20 UTC, angelbruni approved these changes

2024-11-22 20:21 UTC, merged

2024-11-22 20:22 UTC, angelbruni commented
Thanks!